import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Unesio Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons">Unesio Mucutueliua</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill  className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resumo</a>
              </li>
            </ul>
          </nav>

          <div>
            <h2>Unésio Mucutueliua</h2>
            <h3>Desenvolvedor web e Desenvolvedor de aplicações.</h3>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Reiciendis aliquid reprehenderit deserunt rem vitae sint temporibus
                laboriosam sequi fugiat nobis inventore, corporis similique,
                dignissimos quod iure veniam eum quo sunt.
            </p>
          </div>
       </section>
      </main>
    </div>
  );
}
